"use strict";
// Reference tables (header buttons "Tavola periodica" and "Addotti"): periodic table with isotopes, ESI adducts, isotope pattern
// of a formula (computed here), common neutral losses.
// Data of the elements: elements.js (generated by tools/genera_elementi.py). Classic script, after explore.js.
(() => {
  const Qs = s => document.querySelector(s), H = t => String(t).replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
  const ELECTRON = 0.00054858;
  const EL = Object.fromEntries(ELEMENTS.map(e => [e.s, e]));
  // layout of the periodic table: fixed row heights, so the table never changes size; the info box scrolls if needed
  const css = document.createElement("style");
  css.textContent = ".pt{grid-template-rows:repeat(7,46px) 12px repeat(2,46px)!important}.pt-c{height:46px;min-height:0!important;overflow:hidden}" +
    ".pt-info{height:144px;max-height:none!important;min-height:0;overflow:auto;font-size:11px!important;line-height:1.3;padding:2px 10px!important}" +
    ".pt-info table th,.pt-info table td{padding:0 6px!important}.pt-info .pt-big b{font-size:22px}";
  document.head.appendChild(css);
  // monoisotopic mass of an element = exact mass of its most abundant isotope
  const mono = s => { const e = EL[s]; if (!e || !e.iso.length) return null; return e.iso.reduce((a, b) => (b[2] > a[2] ? b : a))[1]; };
  function massOf(f) {                                     // simple formulas, e.g. "CH3COO", "C2H3N"
    let m = 0;
    for (const [, s, n] of f.matchAll(/([A-Z][a-z]?)(\d*)/g)) { const v = mono(s); if (v == null) throw new Error(s); m += v * (n ? +n : 1); }
    return m;
  }
  const sub = f => H(f).replace(/(\d+)/g, "<sub>$1</sub>");

  // ---------------------------------------------------------------- periodic table
  const ORGANIC = new Set(["H", "C", "N", "O", "F", "P", "S", "Cl", "Br", "I", "Na", "K", "Si"]);
  function info(e) {
    const main = e.iso.length ? e.iso.reduce((a, b) => (b[2] > a[2] ? b : a)) : null;
    let h = `<div class="pt-big"><span>${e.z}</span><b>${H(e.s)}</b></div><div><b style="font-size:15px">${H(I18N.t(`el.${e.s}`))}</b></div>
      <div>${I18N.t("tbl.pt.avgWeight", { w: e.w != null ? e.w : I18N.t("tbl.na") })}</div>`;
    if (main) {
      h += `<div>${I18N.t("tbl.pt.mono", { m: main[1].toFixed(5), a: main[0], s: H(e.s) })}</div>
        <table class="sm" style="margin-top:6px"><tr><th>${I18N.t("tbl.pt.col.iso")}</th><th class="num">${I18N.t("tbl.pt.col.mass")}</th><th class="num">${I18N.t("tbl.pt.col.abund")}</th><th class="num">${I18N.t("tbl.pt.col.delta")}</th><th></th></tr>` +
        e.iso.map(i => `<tr><td><sup>${i[0]}</sup>${H(e.s)}</td><td class="num">${i[1] != null ? i[1].toFixed(5) : ""}</td><td class="num">${i[2]}</td>` +
          `<td class="num">${i === main || i[1] == null ? "" : (i[1] - main[1] > 0 ? "+" : "") + (i[1] - main[1]).toFixed(4)}</td>` +
          `<td><i class="pt-bar" style="width:${Math.max(1, Math.round(i[2] * 0.8))}px"></i></td></tr>`).join("") + "</table>";
      if (e.iso.length > 1) {
        const sec = e.iso.filter(i => i !== main).reduce((a, b) => (b[2] > a[2] ? b : a));
        h += `<div class="muted sm" style="margin-top:4px">${I18N.t("tbl.pt.peak", { s: H(e.s), off: (sec[0] - main[0] > 0 ? "+" : "") + (sec[0] - main[0]), pct: (100 * sec[2] / main[2]).toFixed(sec[2] / main[2] < 0.1 ? 1 : 0) })}</div>`;
      }
    } else h += `<div class="muted sm" style="margin-top:6px">${I18N.t("tbl.pt.rare")}</div>`;
    return h;
  }
  function periodic() {
    const cells = ELEMENTS.map(e => `<div class="pt-c${ORGANIC.has(e.s) ? " org" : ""}${e.iso.length ? "" : " nd"}" data-s="${e.s}" style="grid-row:${e.r};grid-column:${e.c}">` +
      `<span>${e.z}</span><b>${e.s}</b><small>${e.w != null ? (e.w < 100 ? e.w.toFixed(3) : e.w.toFixed(2)) : ""}</small></div>`).join("");
    // Data sources (kept here, not shown in the page): exact masses = isotope table of OpenChemLib; abundances = representative
    // isotopic compositions, IUPAC (CIAAW); average atomic weight = Ketcher element list. Hovering an element shows masses and isotopes
    // (click pins it); the most common elements of organic molecules are highlighted.
    return `<div class="pt">${cells}<div class="pt-info" id="pt-info">${info(EL.C)}</div><div class="pt-gap">${I18N.t("tbl.pt.gap")}</div></div>`;
  }
  function bindPeriodic(root) {
    let pinned = null; const box = root.querySelector("#pt-info");
    root.querySelectorAll(".pt-c").forEach(c => {
      c.onmouseenter = () => { if (!pinned) box.innerHTML = info(EL[c.dataset.s]); };
      c.onclick = () => { root.querySelectorAll(".pt-c.pin").forEach(x => x.classList.remove("pin")); if (pinned === c.dataset.s) { pinned = null; return; }
        pinned = c.dataset.s; c.classList.add("pin"); box.innerHTML = info(EL[pinned]); };
    });
  }

  // ---------------------------------------------------------------- adducts
  // k: how many molecules M; add/sub: what is added or removed; z: charge
  const ADD = [
    { n: "[M+H]+", k: 1, add: "H", z: 1, exp: 1, note: "tbl.add.note.mh" },
    { n: "[M+NH4]+", k: 1, add: "NH4", z: 1, exp: 1, note: "tbl.add.note.mnh4" },
    { n: "[M+Na]+", k: 1, add: "Na", z: 1, exp: 1, note: "tbl.add.note.mna" },
    { n: "[M+K]+", k: 1, add: "K", z: 1, exp: 1, note: "tbl.add.note.mk" },
    { n: "[M+H-H2O]+", k: 1, add: "H", sub: "H2O", z: 1, note: "tbl.add.note.mhh2o" },
    { n: "[M+CH3OH+H]+", k: 1, add: "CH5O", z: 1, note: "tbl.add.note.mch3oh" },
    { n: "[M+H+ACN]+", k: 1, add: "C2H4N", z: 1, note: "tbl.add.note.mhacn" },
    { n: "[M+2H]2+", k: 1, add: "H2", z: 2, note: "tbl.add.note.m2h" },
    { n: "[2M+H]+", k: 2, add: "H", z: 1, note: "tbl.add.note.2mh" },
    { n: "[2M+Na]+", k: 2, add: "Na", z: 1, note: "tbl.add.note.2mna" },
    { n: "[M]+", k: 1, add: "", z: 1, note: "tbl.add.note.mcat" },
    { n: "[M]-", k: 1, add: "", z: -1, note: "tbl.add.note.man" },
    { n: "[M-H]-", k: 1, sub: "H", z: -1, exp: 1, note: "tbl.add.note.mminush" },
    { n: "[M+HCOO]-", k: 1, add: "CHO2", z: -1, exp: 1, note: "tbl.add.note.mhcoo" },
    { n: "[M+Cl]-", k: 1, add: "Cl", z: -1, exp: 1, note: "tbl.add.note.mcl" },
    { n: "[M+CH3COO]-", k: 1, add: "C2H3O2", z: -1, note: "tbl.add.note.mch3coo" },
    { n: "[M-H-H2O]-", k: 1, sub: "H3O", z: -1, note: "tbl.add.note.mmhh2o" },
    { n: "[M+Na-2H]-", k: 1, add: "Na", sub: "H2", z: -1, note: "tbl.add.note.mna2h" },
    { n: "[M-2H]2-", k: 1, sub: "H2", z: -2, note: "tbl.add.note.mm2h" },
    { n: "[2M-H]-", k: 2, sub: "H", z: -1, note: "tbl.add.note.2mminush" },
  ];
  ADD.forEach(a => { a.shift = (a.add ? massOf(a.add) : 0) - (a.sub ? massOf(a.sub) : 0) - a.z * ELECTRON; });
  window.QADD = ADD;                                      // for the tests: the shifts are compared with the Python lists
  const mzOf = (a, M) => (a.k * M + a.shift) / Math.abs(a.z);
  const fmtAd = n => H(n).replace(/([A-Z][a-z]?|\))(\d+)/g, "$1<sub>$2</sub>").replace(/(\d?[+-])$/, "<sup>$1</sup>");
  const sgn = x => (x >= 0 ? "+" : "&minus;");
  const AD_MORE = { 1: false, "-1": false };                // the less common adducts stay folded until the student opens them

  // Differences between adducts: to recognise pairs of peaks belonging to the same compound (Huang et al. 1999)
  function calcAdductDiffs() {
    const shift = n => { const a = ADD.find(x => x.n === n); return a ? a.shift : 0; };
    return [
      { p: 1, pair: "[M+Na]+ &minus; [M+H]+", d: shift("[M+Na]+") - shift("[M+H]+"), nom: 22, note: "tbl.diff.note.1", src: "Huang 1999" },
      { p: 1, pair: "[M+NH4]+ &minus; [M+H]+", d: shift("[M+NH4]+") - shift("[M+H]+"), nom: 17, note: "tbl.diff.note.2", src: "Huang 1999" },
      { p: 1, pair: "[M+K]+ &minus; [M+H]+", d: shift("[M+K]+") - shift("[M+H]+"), nom: 38, note: "tbl.diff.note.3", src: "Huang 1999" },
      { p: 1, pair: "[M+K]+ &minus; [M+Na]+", d: shift("[M+K]+") - shift("[M+Na]+"), nom: 16, note: "tbl.diff.note.4", src: "Huang 1999" },
      { p: 1, pair: "[M+H+ACN]+ &minus; [M+H]+", d: shift("[M+H+ACN]+") - shift("[M+H]+"), nom: 41, note: "tbl.diff.note.5", src: "Huang 1999" },
      { p: 1, pair: "[M+CH3OH+H]+ &minus; [M+H]+", d: shift("[M+CH3OH+H]+") - shift("[M+H]+"), nom: 32, note: "tbl.diff.note.6", src: "Huang 1999" },
      { p: 1, pair: "[2M+H]+ &minus; [M+H]+", d: null, nom: "M", note: "tbl.diff.note.7", src: "Huang 1999" },
      { p: 1, pair: "[M+H]+ &minus; [M+H-H2O]+", d: shift("[M+H]+") - shift("[M+H-H2O]+"), nom: 18, note: "tbl.diff.note.8", src: "Huang 1999" },

      { p: -1, pair: "[M+HCOO]&minus; &minus; [M&minus;H]&minus;", d: shift("[M+HCOO]-") - shift("[M-H]-"), nom: 46, note: "tbl.diff.note.9", src: "Huang 1999" },
      { p: -1, pair: "[M+CH3COO]&minus; &minus; [M&minus;H]&minus;", d: shift("[M+CH3COO]-") - shift("[M-H]-"), nom: 60, note: "tbl.diff.note.10", src: "Huang 1999" },
      { p: -1, pair: "[M+Cl]&minus; &minus; [M&minus;H]&minus;", d: shift("[M+Cl]-") - shift("[M-H]-"), nom: 36, note: "tbl.diff.note.11", src: "Huang 1999" },
      { p: -1, pair: "[M+Na-2H]&minus; &minus; [M&minus;H]&minus;", d: shift("[M+Na-2H]-") - shift("[M-H]-"), nom: 22, note: "tbl.diff.note.12", src: "Huang 1999" },
      { p: -1, pair: "[2M&minus;H]&minus; &minus; [M&minus;H]&minus;", d: null, nom: "M", note: "tbl.diff.note.13", src: "Huang 1999" },
      { p: -1, pair: "[M&minus;H]&minus; &minus; [M&minus;H-H2O]&minus;", d: shift("[M-H]-") - shift("[M-H-H2O]-"), nom: 18, note: "tbl.diff.note.14", src: "Huang 1999" },
    ];
  }
  window.QADD_DIFFS = calcAdductDiffs();

  function diffsHtml() {
    const l = calcAdductDiffs();
    const rows = l.map(d => `<tr><td><b>${d.pair}</b></td><td class="num">${d.d != null ? (d.d >= 0 ? "+" : "") + d.d.toFixed(4) : "+M"}</td><td class="num">${d.nom != null ? (typeof d.nom === "number" ? (d.nom >= 0 ? "+" : "") + d.nom : "+" + d.nom) : ""}</td><td class="sm">${d.p > 0 ? "ESI+" : "ESI&minus;"}</td><td class="muted sm">${I18N.t(d.note)}</td></tr>`).join("");
    return `<div style="margin-top:16px"><h4 style="margin:10px 0 4px">${I18N.t("tbl.diff.title")}</h4>
      <div class="muted sm" style="margin-bottom:6px">${I18N.t("tbl.diff.intro")}</div>
      <table><tr><th>${I18N.t("tbl.diff.col.pair")}</th><th class="num">${I18N.t("tbl.diff.col.exact")}</th><th class="num">${I18N.t("tbl.diff.col.nominal")}</th><th>${I18N.t("tbl.diff.col.mode")}</th><th>${I18N.t("tbl.diff.col.note")}</th></tr>${rows}</table></div>`;
  }

  function adducts(M) {
    const ref = { 1: ADD[0], "-1": ADD.find(a => a.n === "[M-H]-") };
    const row = (a, pol) => {
      const expr = `${a.k > 1 ? a.k : ""}M ${sgn(a.shift)} ${Math.abs(a.shift).toFixed(4)}${Math.abs(a.z) > 1 ? I18N.t("tbl.add.divided", { z: Math.abs(a.z) }) : ""}`;
      const d = a === ref[pol] || Math.abs(a.z) > 1 || a.k > 1 ? "" : sgn(a.shift - ref[pol].shift) + Math.abs(a.shift - ref[pol].shift).toFixed(4);
      return `<tr${a.exp ? ' class="exp"' : ""}><td><b>${fmtAd(a.n)}</b></td><td>${expr}</td><td class="num">${M != null ? mzOf(a, M).toFixed(4) : ""}</td><td class="num">${M != null ? rh(mzOf(a, M), 0) : ""}</td><td class="num">${d}</td><td class="muted sm">${I18N.t(a.note)}</td></tr>`;
    };
    const rows = pol => { const l = ADD.filter(a => Math.sign(a.z) === pol);
      return l.filter(a => a.exp).map(a => row(a, pol)).join("") + `<tr class="admore" data-pol="${pol}"><td colspan="6" style="padding-top:8px"><a href="#" class="adtog">${AD_MORE[pol] ? "&#9662;" : "&#9656;"} ${I18N.t("tbl.add.more")}</a></td></tr>` + (AD_MORE[pol] ? l.filter(a => !a.exp).map(a => row(a, pol)).join("") : ""); };
    const head = pol => `<tr><th>${I18N.t("tbl.add.col.adduct")}</th><th>m/z =</th><th class="num">${I18N.t("tbl.add.col.exact")}</th><th class="num">${I18N.t("tbl.add.col.nominal")}</th><th class="num">${I18N.t("tbl.add.col.delta", { ref: pol > 0 ? "[M+H]<sup>+</sup>" : "[M&minus;H]<sup>&minus;</sup>" })}</th><th>${I18N.t("tbl.add.col.when")}</th></tr>`;
    const blk = pol => `<h4>${I18N.t(pol > 0 ? "tbl.add.esiPos" : "tbl.add.esiNeg")}</h4><table>${head(pol)}${rows(pol)}</table>`;
    const neg = typeof E !== "undefined" && E.files.some(f => f.polarity === "negative") && !E.files.some(f => f.polarity === "positive");      // the polarity of the loaded files first
    return (neg ? blk(-1) + blk(1) : blk(1) + blk(-1)) + diffsHtml();
  }
  function adductTab() {
    return `<div class="bar"><label>${I18N.t("tbl.add.input")} <input id="ad-in" placeholder="${I18N.t("tbl.add.placeholder")}" style="width:260px"></label><span id="ad-msg" class="muted sm"></span></div>
      <div class="sm">${I18N.t("tbl.add.intro")}</div>
      <div id="ad-tbl">${adducts(null)}</div>`;
  }
  function bindAdducts(root) {
    const inp = root.querySelector("#ad-in"), msg = root.querySelector("#ad-msg"), tb = root.querySelector("#ad-tbl");
    let lastM = null;                                               // the table is rebuilt at every keystroke: the open / folded state lives in AD_MORE
    const redo = () => { tb.innerHTML = adducts(lastM); };
    tb.onclick = e => { const t = e.target.closest(".adtog"); if (!t) return; e.preventDefault(); const pol = t.closest("tr").dataset.pol; AD_MORE[pol] = !AD_MORE[pol]; redo(); };
    inp.oninput = async () => {
      const t = inp.value.trim().replace(",", ".");
      if (!t) { msg.textContent = ""; lastM = null; redo(); return; }
      if (/^\d+(\.\d*)?$/.test(t)) { msg.textContent = ""; lastM = +t; redo(); return; }
      try { const r = await (await fetch("api/formula?f=" + encodeURIComponent(t))).json(); if (r.error) throw new Error(r.error);
        let M = r.neutral; try { M = massOf(r.formula); } catch (_) { /* element without isotope data here: use the server value */ }
        msg.innerHTML = `${sub(r.formula)}: M = ${M.toFixed(4)}`; lastM = M; redo(); }
      catch (e) { msg.textContent = I18N.t("tbl.add.invalid"); lastM = null; redo(); }
    };
  }

  // ---------------------------------------------------------------- common neutral losses (MS/MS and in-source)
  // The masses are computed from the formulas (exact mass rounded to the integer); the "typical of" column summarises what the reviews below
  // describe for even-electron ions in ESI-MS/MS. A loss is only a hypothesis: it must be checked against the structure.
  function lossRefs() {
    const L = (u, t) => `<a href="${u}" target="_blank" rel="noopener">${t}</a>`;
    return `<div class="muted sm" style="margin-top:8px"><b>${I18N.t("tbl.loss.refs")}</b><ol style="margin:4px 0 0 18px;padding:0;line-height:1.5">
      <li>Levsen K., Schiebel H.-M., Terlouw J. K., et al. <i>Even-electron ions: a systematic study of the neutral species lost in the dissociation of quasi-molecular ions.</i> J. Mass Spectrom. 2007, 42, 1024-1044. ${L("https://analyticalsciencejournals.onlinelibrary.wiley.com/doi/10.1002/jms.1234", "link")}</li>
      <li>De Vijlder T., Valkenborg D., Lemi&egrave;re F., Romijn E. P., Laukens K., Cuyckens F. <i>A tutorial in small molecule identification via electrospray ionization-mass spectrometry: the practical art of structural elucidation.</i> Mass Spectrom. Rev. 2018, 37, 607-629. ${L("https://pmc.ncbi.nlm.nih.gov/articles/PMC6099382/", I18N.t("tbl.loss.refFree"))}</li>
      <li>Demarque D. P., Crotti A. E. M., Vessecchi R., Lopes J. L. C., Lopes N. P. <i>Fragmentation reactions using electrospray ionization mass spectrometry: an important tool for the structural elucidation and characterization of synthetic and natural products.</i> Nat. Prod. Rep. 2016, 33, 432-455. ${L("https://pubs.rsc.org/en/content/articlelanding/2016/np/c5np00073d", "link")}</li>
      <li>Hol&ccaron;apek M., Jir&aacute;sko R., L&iacute;sa M. <i>Basic rules for the interpretation of atmospheric pressure ionization mass spectra of small molecules.</i> J. Chromatogr. A 2010, 1217, 3908-3921. ${L("https://pubmed.ncbi.nlm.nih.gov/20303090/", "link")}</li></ol></div>`;
  }
  // «Perdite neutre»: one line per loss (Δm, formula, name, where it is seen, typical polarity); «Dettagli» opens exact mass, mechanism and source;
  // the losses with the same nominal mass sit in a box (unit resolution cannot tell them apart); «Cerca Δm» lists single, pair and repeated candidates.
  const NL = { q: "", pol: "", open: new Set(), more: false };       // state kept while the window is open (the ruler of the spectrum can fill q)
  const fl = f => sub(f.replace(/^(CH3|NO2|Cl)$/, "•$1")).replace(/^•/, "•");   // radicals are written with the dot
  // high resolution (an Orbitrap / Q-TOF file is loaded): the exact mass of each loss is shown and «Cerca Δm» looks within 3 mDa instead of 0.5 Da
  const hrOn = () => !!(window.HR && typeof E !== "undefined" && E.files.some(f => !f.gone && (HR.isHr(f, 1) || HR.isHr(f, 2))));
  const NL_TOL = () => hrOn() ? 0.003 : 0.5, NL_DEC = () => hrOn() ? 4 : 1;
  const polChip = p => {
    const cls = p === "+" ? "pol pos" : p === "-" ? "pol neg" : "pol both";
    const txt = p === "+" ? "ESI+" : p === "-" ? "ESI&minus;" : "ESI+/-";
    const tip = I18N.t(p === "+" ? "tbl.loss.polPos" : p === "-" ? "tbl.loss.polNeg" : "tbl.loss.polBoth");
    return `<span class="${cls}" title="${tip}">${txt}</span>`;
  };
  const lossRow = (l, o) => {
    const m = massOf(l.f), id = l.f;
    return `<div class="nlr${o.hit.has(id) ? " hit" : ""}" data-f="${id}"><div class="nlm">${Math.round(m)}${hrOn() ? `<small class="muted" title="${I18N.t("tbl.loss.exactTitle")}" style="display:block;font-size:10.5px;font-weight:400">${m.toFixed(4)}</small>` : ""}</div><div class="nlf"><b>${fl(l.f)}</b><span class="muted">${H(I18N.t(l.name))}</span></div>
      <div class="nls">${H(I18N.t(l.seen))}</div><div class="nlpp">${polChip(l.pol)}</div><button class="nld" type="button" data-d="${id}" aria-expanded="${NL.open.has(id)}">${I18N.t("tbl.loss.details")}</button>
      ${l.rad ? `<div class="nlrad">• ${H(I18N.t(LOSS_RAD))}</div>` : ""}
      <div class="nldet"${NL.open.has(id) ? "" : " hidden"}><div>${I18N.t("tbl.loss.detail", { m: m.toFixed(4), mech: H(I18N.t(l.mech)) })}</div><div class="muted sm">${I18N.t(l.rad ? "tbl.loss.sourcesRad" : "tbl.loss.sources", { refs: H(LOSS_REFS) })}</div></div></div>`;
  };
  function lossList() {
    const hit = new Set(), q = parseFloat(String(NL.q).replace(",", "."));
    const vis = LOSSES.filter(l => !NL.pol || l.pol === "±" || l.pol === NL.pol).sort((a, b) => massOf(a.f) - massOf(b.f));
    if (isFinite(q)) vis.forEach(l => { if (Math.abs(massOf(l.f) - q) <= NL_TOL()) hit.add(l.f); });
    const groups = []; vis.forEach(l => { const n = Math.round(massOf(l.f)), g = groups[groups.length - 1]; if (g && g.n === n) g.ls.push(l); else groups.push({ n, ls: [l] }); });
    return groups.map(g => g.ls.length < 2 ? lossRow(g.ls[0], { hit }) : `<div class="nlg"><div class="nlgn">${I18N.t("tbl.loss.sameNominal", { n: g.n })}${g.n === 80 ? " " + I18N.t("tbl.loss.checkM2") : ""}</div>${g.ls.map(l => lossRow(l, { hit })).join("")}</div>`).join("");
  }
  function lossCombosHtml() {
    const q = parseFloat(String(NL.q).replace(",", ".")); if (!isFinite(q) || q <= 0) return "";
    const c = lossCombos(q, massOf, NL_TOL()), nm = l => `<b>${fl(l.f)}</b>`, nd = NL_DEC();
    const li = [...c.single.map(x => `<li>${nm(x[0])} <span class="muted">(${massOf(x[0].f).toFixed(nd)})</span></li>`), ...c.pairs.map(p => `<li>${nm(p[0])} + ${nm(p[1])} <span class="muted">(${(massOf(p[0].f) + massOf(p[1].f)).toFixed(nd)})</span></li>`), ...c.reps.map(r => `<li>${r.n} &times; ${nm(r.l)} <span class="muted">(${(r.n * massOf(r.l.f)).toFixed(nd)})</span></li>`)];
    return `<div class="nlc"><b>${I18N.t("tbl.loss.possible")}</b>${li.length ? `<ul>${li.join("")}</ul>` : `<div class="muted sm">${I18N.t("tbl.loss.none", { tol: hrOn() ? "0.003" : "0.5" })}</div>`}</div>`;
  }
  function lossTab() {
    return `<div class="nlintro"><p>${I18N.t("tbl.loss.intro")}</p>
      <a href="#" id="nl-more-t" aria-expanded="${NL.more}">${NL.more ? "&#9662;" : "&#9656;"} ${I18N.t("tbl.loss.moreLink")}</a>
      <p id="nl-more"${NL.more ? "" : " hidden"}>${I18N.t("tbl.loss.more")}</p></div>
      <div class="nlbar"><label>${I18N.t("tbl.loss.search")} <input id="nl-q" inputmode="decimal" autocomplete="off" placeholder="${I18N.t("tbl.loss.searchPh")}" value="${H(NL.q)}" title="${I18N.t("tbl.loss.searchTitle")}"></label>
      <span class="seg" id="nl-pol" title="${I18N.t("tbl.loss.polTitle")}"><button data-p="+" class="${NL.pol === "+" ? "on" : ""}">ESI+</button><button data-p="-" class="${NL.pol === "-" ? "on" : ""}">ESI&minus;</button><button data-p="" class="${NL.pol === "" ? "on" : ""}">${I18N.t("tbl.loss.all")}</button></span></div>
      <div id="nl-res">${lossCombosHtml()}</div><div id="nl-list">${lossList()}</div>` + lossRefs();
  }
  function bindLoss(root, show) {
    const list = () => { root.querySelector("#nl-list").innerHTML = lossList(); wire(); root.querySelector("#nl-res").innerHTML = lossCombosHtml(); };
    const wire = () => {
      root.querySelectorAll(".nld").forEach(b => b.onclick = () => { const id = b.dataset.d, row = b.closest(".nlr"), d = row.querySelector(".nldet"); if (NL.open.has(id)) NL.open.delete(id); else NL.open.add(id); d.hidden = !NL.open.has(id); b.setAttribute("aria-expanded", NL.open.has(id)); });
      root.querySelectorAll("[data-go]").forEach(a => a.onclick = e => { e.preventDefault(); show(a.dataset.go); });
    };
    wire();
    root.querySelector("#nl-more-t").onclick = e => { e.preventDefault(); NL.more = !NL.more; root.querySelector("#nl-more").hidden = !NL.more; e.currentTarget.setAttribute("aria-expanded", NL.more); e.currentTarget.innerHTML = (NL.more ? "&#9662;" : "&#9656;") + " " + I18N.t("tbl.loss.moreLink"); };
    root.querySelector("#nl-q").oninput = e => { NL.q = e.target.value; list(); };
    root.querySelectorAll("#nl-pol button").forEach(b => b.onclick = () => { NL.pol = b.dataset.p; root.querySelectorAll("#nl-pol button").forEach(x => x.classList.toggle("on", x === b)); list(); });
  }
  // the polarity of the loaded files sets the filter when the window opens (the student can change it)
  function lossPolStart() {
    try { const fl = typeof shown === "function" && shown().length ? shown() : E.files.filter(f => f.vis), pos = fl.some(f => f.polarity === "positive"), neg = fl.some(f => f.polarity === "negative"); NL.pol = pos && !neg ? "+" : neg && !pos ? "-" : ""; } catch (_) { NL.pol = ""; }
  }

  // ---------------------------------------------------------------- isotope pattern, computed here (no external library)
  // Unit resolution: isotopologues are grouped by nominal mass offset (M, M+1, M+2...); in each group we keep the total
  // probability and the probability-weighted exact mass. Elements are combined by convolution (n atoms: by squaring).
  const counts = f => { const n = {}; for (const [, s, k] of f.matchAll(/([A-Z][a-z]?)(\d*)/g)) n[s] = (n[s] || 0) + (k ? +k : 1); return n; };
  const PRUNE = 1e-9, MAXOFF = 40;
  function conv(a, b) {                                    // a, b: Map(offset -> [probability, mass x probability])
    const out = new Map();
    for (const [oa, [pa, ma]] of a) for (const [ob, [pb, mb]] of b) {
      const o = oa + ob; if (o > MAXOFF) continue;
      const p = pa * pb; if (p < PRUNE) continue;
      const cur = out.get(o) || [0, 0];
      cur[0] += p; cur[1] += ma * pb + mb * pa;            // mean mass of the group adds up: E[ma+mb]
      out.set(o, cur);
    }
    return out;
  }
  function elementDist(s) {
    const e = EL[s]; if (!e || !e.iso.length) throw new Error(I18N.t("tbl.iso.unavailable", { s }));
    const main = e.iso.reduce((a, b) => (b[2] > a[2] ? b : a)), d = new Map();
    for (const [A, m, pct] of e.iso) { const p = pct / 100; if (m == null || p <= 0) continue; const o = A - main[0]; d.set(o, [p, m * p]); }
    // keep only non-negative offsets relative to the lightest isotope: shift so the lightest is 0
    const o0 = Math.min(...d.keys()), out = new Map(); for (const [o, v] of d) out.set(o - o0, v); return out;
  }
  function power(d, n) {
    let res = new Map([[0, [1, 0]]]), base = d;
    while (n > 0) { if (n & 1) res = conv(res, base); n >>= 1; if (n) base = conv(base, base); }
    return res;
  }
  // pattern of an ion: element counts (already including the adduct) and charge z -> [{off, mz, rel}] (rel: % of the highest)
  function isoPattern(n, z = 1) {
    let dist = new Map([[0, [1, 0]]]);
    for (const [s, k] of Object.entries(n)) if (k > 0) dist = conv(dist, power(elementDist(s), k));
    const rows = [...dist].map(([o, [p, mp]]) => ({ off: o, p, mz: (mp / p - z * ELECTRON) / Math.abs(z) }));
    const top = Math.max(...rows.map(r => r.p));
    return rows.map(r => ({ off: r.off, mz: r.mz, rel: 100 * r.p / top })).filter(r => r.rel >= 0.05).sort((a, b) => a.mz - b.mz);
  }
  // neutral formula (Hill, no parentheses) + adduct name -> element counts of the ion and its charge
  function ionCounts(formula, adName) {
    const a = ADD.find(x => x.n === adName) || ADD[0], n = {}, M = counts(formula);
    for (const [s, k] of Object.entries(M)) n[s] = k * a.k;
    if (a.add) for (const [s, k] of Object.entries(counts(a.add))) n[s] = (n[s] || 0) + k;
    if (a.sub) for (const [s, k] of Object.entries(counts(a.sub))) n[s] = (n[s] || 0) - k;
    if (Object.values(n).some(k => k < 0)) throw new Error(I18N.t("tbl.iso.adductTooMany"));
    return { n, z: a.z, ad: a.n };
  }
  // ---------------------------------------------------------------- dialog with three tabs (Tavola periodica, Addotti, Perdite neutre)
  const TABS = [["pt", I18N.t("icon.pt"), periodic, bindPeriodic], ["ad", I18N.t("icon.adduct"), adductTab, bindAdducts], ["ls", I18N.t("icon.nl"), lossTab, bindLoss]];
  function open(which, opt = {}) {
    const d = Qs("#refdlg"), body = Qs("#refbody");
    if (which === "ls") { if (!d.open) lossPolStart(); if (opt.q != null) NL.q = String(opt.q); }
    const show = id => {
      const t = TABS.find(x => x[0] === id); body.innerHTML = t[2](); if (t[3]) t[3](body, show);
      d.querySelectorAll("#reftabs button").forEach(b => b.classList.toggle("on", b.dataset.t === id));
    };
    Qs("#reftabs").innerHTML = TABS.map(t => `<button data-t="${t[0]}">${t[1]}</button>`).join("");
    Qs("#reftabs").querySelectorAll("button").forEach(b => b.onclick = () => show(b.dataset.t));
    Qs("#refx").onclick = () => d.close();
    show(which); if (!d.open) d.showModal();
    if (which === "ls" && opt.q != null) setTimeout(() => { const i = body.querySelector("#nl-q"); if (i) { i.focus(); i.select(); } }, 50);
  }
  function mountLosses(container, opt = {}) {
    lossPolStart();
    if (opt.q != null) NL.q = String(opt.q);
    container.innerHTML = lossTab();
    bindLoss(container, id => {
      if (id === "pt" || id === "ad") {
        if (window.BARRA && BARRA.isDataView()) {
          BARRA.setTab(id === "pt" ? "ptable" : "adducts");
        } else {
          open(id);
        }
      }
    });
    if (opt.q != null) {
      setTimeout(() => { const i = container.querySelector("#nl-q"); if (i) { i.focus(); i.select(); } }, 50);
    }
  }

  function mountAdducts(container) {
    container.innerHTML = adductTab();
    bindAdducts(container);
  }

  function setLossQuery(q) {
    NL.q = String(q || "");
    const qInp = document.querySelector("#nl-q");
    if (qInp) {
      qInp.value = NL.q;
      qInp.dispatchEvent(new Event("input", { bubbles: true }));
      setTimeout(() => { qInp.focus(); qInp.select(); }, 50);
    }
  }

  Qs("#np-pt").onclick = () => open("pt");
  Qs("#np-ad").onclick = () => {
    if (window.BARRA && BARRA.isDataView()) BARRA.setTab("adducts");
    else open("ad");
  };
  Qs("#np-nl").onclick = () => {
    if (window.BARRA && BARRA.isDataView()) BARRA.setTab("losses");
    else open("ls");
  };
  window.QQQRef = {
    open, massOf, mono, isoPattern, ionCounts, ADD, adductDiffs: calcAdductDiffs,
    mountLosses, mountAdducts, setLossQuery, periodic, bindPeriodic, adductTab, bindAdducts, lossTab, bindLoss
  };
})();
