"use strict";
// Reference tables (header buttons "Tavola periodica" and "Addotti"): periodic table with isotopes, ESI adducts, isotope pattern
// of a formula (computed here), common neutral losses.
// Data of the elements: elements.js (generated by tools/genera_elementi.py). Classic script, after explore.js.
(() => {
  const Qs = s => document.querySelector(s), H = t => String(t).replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
  const ELECTRON = 0.00054858;
  const EL = Object.fromEntries(ELEMENTS.map(e => [e.s, e]));
  // layout of the periodic table: fixed row heights, so the table never changes size; the info box scrolls if needed
  const css = document.createElement("style");
  css.textContent = ".pt{grid-template-rows:repeat(7,46px) 12px repeat(2,46px)!important}.pt-c{height:46px;min-height:0!important;overflow:hidden}" +
    ".pt-info{height:144px;max-height:none!important;min-height:0;overflow:auto;font-size:11px!important;line-height:1.3;padding:2px 10px!important}" +
    ".pt-info table th,.pt-info table td{padding:0 6px!important}.pt-info .pt-big b{font-size:22px}";
  document.head.appendChild(css);
  // monoisotopic mass of an element = exact mass of its most abundant isotope
  const mono = s => { const e = EL[s]; if (!e || !e.iso.length) return null; return e.iso.reduce((a, b) => (b[2] > a[2] ? b : a))[1]; };
  function massOf(f) {                                     // simple formulas, e.g. "CH3COO", "C2H3N"
    let m = 0;
    for (const [, s, n] of f.matchAll(/([A-Z][a-z]?)(\d*)/g)) { const v = mono(s); if (v == null) throw new Error(s); m += v * (n ? +n : 1); }
    return m;
  }
  const sub = f => H(f).replace(/(\d+)/g, "<sub>$1</sub>");

  // ---------------------------------------------------------------- periodic table
  const ORGANIC = new Set(["H", "C", "N", "O", "F", "P", "S", "Cl", "Br", "I", "Na", "K", "Si"]);
  function info(e) {
    const main = e.iso.length ? e.iso.reduce((a, b) => (b[2] > a[2] ? b : a)) : null;
    let h = `<div class="pt-big"><span>${e.z}</span><b>${H(e.s)}</b></div><div><b style="font-size:15px">${H(e.n)}</b></div>
      <div>peso atomico medio <b>${e.w != null ? e.w : "n.d."}</b> <span class="muted">(media pesata sugli isotopi naturali)</span></div>`;
    if (main) {
      h += `<div>massa monoisotopica <b>${main[1].toFixed(5)}</b> <span class="muted">(<sup>${main[0]}</sup>${H(e.s)}, l'isotopo più abbondante: è quella che si usa in MS)</span></div>
        <table class="sm" style="margin-top:6px"><tr><th>isotopo</th><th class="num">massa esatta</th><th class="num">abbondanza %</th><th class="num">&Delta; dal principale</th><th></th></tr>` +
        e.iso.map(i => `<tr><td><sup>${i[0]}</sup>${H(e.s)}</td><td class="num">${i[1] != null ? i[1].toFixed(5) : ""}</td><td class="num">${i[2]}</td>` +
          `<td class="num">${i === main || i[1] == null ? "" : (i[1] - main[1] > 0 ? "+" : "") + (i[1] - main[1]).toFixed(4)}</td>` +
          `<td><i class="pt-bar" style="width:${Math.max(1, Math.round(i[2] * 0.8))}px"></i></td></tr>`).join("") + "</table>";
      if (e.iso.length > 1) {
        const sec = e.iso.filter(i => i !== main).reduce((a, b) => (b[2] > a[2] ? b : a));
        h += `<div class="muted sm" style="margin-top:4px">Ogni atomo di ${H(e.s)} nella molecola dà un picco a ${sec[0] - main[0] > 0 ? "+" : ""}${sec[0] - main[0]} con circa il ${(100 * sec[2] / main[2]).toFixed(sec[2] / main[2] < 0.1 ? 1 : 0)}% dell'intensità del picco principale.</div>`;
      }
    } else h += `<div class="muted sm" style="margin-top:6px">Elemento raro in LC-MS: abbondanze isotopiche non incluse nel programma.</div>`;
    return h;
  }
  function periodic() {
    const cells = ELEMENTS.map(e => `<div class="pt-c${ORGANIC.has(e.s) ? " org" : ""}${e.iso.length ? "" : " nd"}" data-s="${e.s}" style="grid-row:${e.r};grid-column:${e.c}">` +
      `<span>${e.z}</span><b>${e.s}</b><small>${e.w != null ? (e.w < 100 ? e.w.toFixed(3) : e.w.toFixed(2)) : ""}</small></div>`).join("");
    // Data sources (kept here, not shown in the page): exact masses = isotope table of OpenChemLib; abundances = representative
    // isotopic compositions, IUPAC (CIAAW); average atomic weight = Ketcher element list. Hovering an element shows masses and isotopes
    // (click pins it); the most common elements of organic molecules are highlighted.
    return `<div class="pt">${cells}<div class="pt-info" id="pt-info">${info(EL.C)}</div><div class="pt-gap">lantanidi e attinidi</div></div>`;
  }
  function bindPeriodic(root) {
    let pinned = null; const box = root.querySelector("#pt-info");
    root.querySelectorAll(".pt-c").forEach(c => {
      c.onmouseenter = () => { if (!pinned) box.innerHTML = info(EL[c.dataset.s]); };
      c.onclick = () => { root.querySelectorAll(".pt-c.pin").forEach(x => x.classList.remove("pin")); if (pinned === c.dataset.s) { pinned = null; return; }
        pinned = c.dataset.s; c.classList.add("pin"); box.innerHTML = info(EL[pinned]); };
    });
  }

  // ---------------------------------------------------------------- adducts
  // k: how many molecules M; add/sub: what is added or removed; z: charge
  const ADD = [
    { n: "[M+H]+", k: 1, add: "H", z: 1, exp: 1, note: "lo ione più comune in ESI+ con acido formico in fase mobile (come in questo laboratorio)" },
    { n: "[M+NH4]+", k: 1, add: "NH4", z: 1, exp: 1, note: "solo se la fase mobile contiene ammonio (formiato, acetato); tipico di esteri, chetoni, zuccheri" },
    { n: "[M+Na]+", k: 1, add: "Na", z: 1, exp: 1, note: "sodio da vetreria, acqua, campione: frequentissimo; frammenta poco in MS/MS" },
    { n: "[M+K]+", k: 1, add: "K", z: 1, exp: 1, note: "come il sodio, meno intenso" },
    { n: "[M+H-H2O]+", k: 1, add: "H", sub: "H2O", z: 1, note: "perdita d'acqua in sorgente (alcoli, acidi carbossilici)" },
    { n: "[M+CH3OH+H]+", k: 1, add: "CH5O", z: 1, note: "con metanolo in fase mobile" },
    { n: "[M+H+ACN]+", k: 1, add: "C2H4N", z: 1, note: "con acetonitrile in fase mobile" },
    { n: "[M+2H]2+", k: 1, add: "H2", z: 2, note: "carica doppia: m/z circa dimezzato, isotopi distanti 0.5" },
    { n: "[2M+H]+", k: 2, add: "H", z: 1, note: "dimero: compare a concentrazioni alte" },
    { n: "[2M+Na]+", k: 2, add: "Na", z: 1, note: "dimero con sodio" },
    { n: "[M]+", k: 1, add: "", z: 1, note: "catione già formato (es. ammonio quaternario): si inserisce la formula del <b>catione</b>, perché la massa sottrae l'elettrone. Per il radicale catione M<sup>+&bull;</sup> si inserisce invece la formula della molecola <b>neutra</b>" },
    { n: "[M-H]-", k: 1, sub: "H", z: -1, exp: 1, note: "lo ione più comune in ESI&minus; (acidi, fenoli, sulfonati)" },
    { n: "[M+HCOO]-", k: 1, add: "CHO2", z: -1, exp: 1, note: "con acido formico in fase mobile" },
    { n: "[M+Cl]-", k: 1, add: "Cl", z: -1, exp: 1, note: "con solventi clorurati o campioni salini (cerca la coppia 35/37 a 3:1)" },
    { n: "[M+CH3COO]-", k: 1, add: "C2H3O2", z: -1, note: "con acido acetico o acetato di ammonio" },
    { n: "[M-H-H2O]-", k: 1, sub: "H3O", z: -1, note: "perdita d'acqua in sorgente" },
    { n: "[M+Na-2H]-", k: 1, add: "Na", sub: "H2", z: -1, note: "sale sodico" },
    { n: "[M-2H]2-", k: 1, sub: "H2", z: -2, note: "carica doppia" },
    { n: "[2M-H]-", k: 2, sub: "H", z: -1, note: "dimero" },
  ];
  ADD.forEach(a => { a.shift = (a.add ? massOf(a.add) : 0) - (a.sub ? massOf(a.sub) : 0) - a.z * ELECTRON; });
  window.QADD = ADD;                                      // for the tests: the shifts are compared with the Python lists
  const mzOf = (a, M) => (a.k * M + a.shift) / Math.abs(a.z);
  const fmtAd = n => H(n).replace(/([A-Z][a-z]?|\))(\d+)/g, "$1<sub>$2</sub>").replace(/(\d?[+-])$/, "<sup>$1</sup>");
  const sgn = x => (x >= 0 ? "+" : "&minus;");
  const AD_MORE = { 1: false, "-1": false };                // the less common adducts stay folded until the student opens them
  function adducts(M) {
    const ref = { 1: ADD[0], "-1": ADD.find(a => a.n === "[M-H]-") };
    const row = (a, pol) => {
      const expr = `${a.k > 1 ? a.k : ""}M ${sgn(a.shift)} ${Math.abs(a.shift).toFixed(4)}${Math.abs(a.z) > 1 ? `, diviso ${Math.abs(a.z)}` : ""}`;
      const d = a === ref[pol] || Math.abs(a.z) > 1 || a.k > 1 ? "" : sgn(a.shift - ref[pol].shift) + Math.abs(a.shift - ref[pol].shift).toFixed(4);
      return `<tr${a.exp ? ' class="exp"' : ""}><td><b>${fmtAd(a.n)}</b></td><td>${expr}</td><td class="num">${M != null ? mzOf(a, M).toFixed(4) : ""}</td><td class="num">${M != null ? rh(mzOf(a, M), 0) : ""}</td><td class="num">${d}</td><td class="muted sm">${a.note}</td></tr>`;
    };
    const rows = pol => { const l = ADD.filter(a => Math.sign(a.z) === pol);
      return l.filter(a => a.exp).map(a => row(a, pol)).join("") + `<tr class="admore" data-pol="${pol}"><td colspan="6" style="padding-top:8px"><a href="#" class="adtog">${AD_MORE[pol] ? "&#9662;" : "&#9656;"} Altri addotti (meno comuni)</a></td></tr>` + (AD_MORE[pol] ? l.filter(a => !a.exp).map(a => row(a, pol)).join("") : ""); };
    const head = pol => `<tr><th>addotto</th><th>m/z =</th><th class="num">m/z esatto</th><th class="num"><i>m/z</i> nominale</th><th class="num">&Delta; da ${pol > 0 ? "[M+H]<sup>+</sup>" : "[M&minus;H]<sup>&minus;</sup>"}</th><th>quando si vede</th></tr>`;
    const blk = pol => `<h4>${pol > 0 ? "ESI positivo" : "ESI negativo"}</h4><table>${head(pol)}${rows(pol)}</table>`;
    const neg = typeof E !== "undefined" && E.files.some(f => f.polarity === "negative") && !E.files.some(f => f.polarity === "positive");      // the polarity of the loaded files first
    return neg ? blk(-1) + blk(1) : blk(1) + blk(-1);
  }
  function adductTab() {
    return `<div class="bar"><label>M (massa neutra) o formula <input id="ad-in" placeholder="es. 363.0665 oppure C14H13F4N3O2S" style="width:260px"></label><span id="ad-msg" class="muted sm"></span></div>
      <div class="sm">Un <b>addotto</b> è lo ione che la molecola M forma nella sorgente legandosi a un piccolo ione presente in soluzione (H<sup>+</sup>, Na<sup>+</sup>, NH<sub>4</sub><sup>+</sup>, K<sup>+</sup> in positivo; HCOO<sup>−</sup> o Cl<sup>−</sup> in negativo) o cedendo un protone ([M−H]<sup>−</sup>). Nello spettro non si vede M, ma l'm/z dei suoi addotti: per questo lo stesso composto può dare più picchi, sempre alla stessa distanza fra loro (per esempio circa 22 tra [M+H]<sup>+</sup> e [M+Na]<sup>+</sup>).</div>
      <div id="ad-tbl">${adducts(null)}</div>`;
  }
  function bindAdducts(root) {
    const inp = root.querySelector("#ad-in"), msg = root.querySelector("#ad-msg"), tb = root.querySelector("#ad-tbl");
    let lastM = null;                                               // the table is rebuilt at every keystroke: the open / folded state lives in AD_MORE
    const redo = () => { tb.innerHTML = adducts(lastM); };
    tb.onclick = e => { const t = e.target.closest(".adtog"); if (!t) return; e.preventDefault(); const pol = t.closest("tr").dataset.pol; AD_MORE[pol] = !AD_MORE[pol]; redo(); };
    inp.oninput = async () => {
      const t = inp.value.trim().replace(",", ".");
      if (!t) { msg.textContent = ""; lastM = null; redo(); return; }
      if (/^\d+(\.\d*)?$/.test(t)) { msg.textContent = ""; lastM = +t; redo(); return; }
      try { const r = await (await fetch("api/formula?f=" + encodeURIComponent(t))).json(); if (r.error) throw new Error(r.error);
        let M = r.neutral; try { M = massOf(r.formula); } catch (_) { /* element without isotope data here: use the server value */ }
        msg.innerHTML = `${sub(r.formula)}: M = ${M.toFixed(4)}`; lastM = M; redo(); }
      catch (e) { msg.textContent = "formula non valida"; lastM = null; redo(); }
    };
  }

  // ---------------------------------------------------------------- common neutral losses (MS/MS and in-source)
  // The masses are computed from the formulas (exact mass rounded to the integer); the "typical of" column summarises what the reviews below
  // describe for even-electron ions in ESI-MS/MS. A loss is only a hypothesis: it must be checked against the structure.
  function lossRefs() {
    const L = (u, t) => `<a href="${u}" target="_blank" rel="noopener">${t}</a>`;
    return `<div class="muted sm" style="margin-top:8px"><b>Riferimenti</b><ol style="margin:4px 0 0 18px;padding:0;line-height:1.5">
      <li>Levsen K., Schiebel H.-M., Terlouw J. K., et al. <i>Even-electron ions: a systematic study of the neutral species lost in the dissociation of quasi-molecular ions.</i> J. Mass Spectrom. 2007, 42, 1024-1044. ${L("https://analyticalsciencejournals.onlinelibrary.wiley.com/doi/10.1002/jms.1234", "link")}</li>
      <li>De Vijlder T., Valkenborg D., Lemi&egrave;re F., Romijn E. P., Laukens K., Cuyckens F. <i>A tutorial in small molecule identification via electrospray ionization-mass spectrometry: the practical art of structural elucidation.</i> Mass Spectrom. Rev. 2018, 37, 607-629. ${L("https://pmc.ncbi.nlm.nih.gov/articles/PMC6099382/", "link (accesso libero)")}</li>
      <li>Demarque D. P., Crotti A. E. M., Vessecchi R., Lopes J. L. C., Lopes N. P. <i>Fragmentation reactions using electrospray ionization mass spectrometry: an important tool for the structural elucidation and characterization of synthetic and natural products.</i> Nat. Prod. Rep. 2016, 33, 432-455. ${L("https://pubs.rsc.org/en/content/articlelanding/2016/np/c5np00073d", "link")}</li>
      <li>Hol&ccaron;apek M., Jir&aacute;sko R., L&iacute;sa M. <i>Basic rules for the interpretation of atmospheric pressure ionization mass spectra of small molecules.</i> J. Chromatogr. A 2010, 1217, 3908-3921. ${L("https://pubmed.ncbi.nlm.nih.gov/20303090/", "link")}</li></ol></div>`;
  }
  // «Perdite neutre»: one line per loss (Δm, formula, name, where it is seen, typical polarity); «Dettagli» opens exact mass, mechanism and source;
  // the losses with the same nominal mass sit in a box (unit resolution cannot tell them apart); «Cerca Δm» lists single, pair and repeated candidates.
  const NL = { q: "", pol: "", open: new Set() };       // state kept while the window is open (the ruler of the spectrum can fill q)
  const fl = f => sub(f.replace(/^(CH3|NO2)$/, "•$1")).replace(/^•/, "•");   // radicals are written with the dot
  const polChip = p => (p === "±" ? "<i class='nlp'>+</i><i class='nlp'>&minus;</i>" : p === "+" ? "<i class='nlp'>+</i>" : "<i class='nlp'>&minus;</i>");
  const lossRow = (l, o) => {
    const m = massOf(l.f), id = l.f;
    return `<div class="nlr${o.hit.has(id) ? " hit" : ""}" data-f="${id}"><div class="nlm">${Math.round(m)}</div><div class="nlf"><b>${fl(l.f)}</b><span class="muted">${H(l.name)}</span></div>
      <div class="nls">${H(l.seen)}</div><div class="nlpp">${polChip(l.pol)}</div><button class="nld" type="button" data-d="${id}" aria-expanded="${NL.open.has(id)}">Dettagli</button>
      ${l.rad ? `<div class="nlrad">• ${H(LOSS_RAD)}</div>` : ""}
      <div class="nldet"${NL.open.has(id) ? "" : " hidden"}><div>massa esatta <b>${m.toFixed(4)}</b> · <span class="muted">meccanismo:</span> ${H(l.mech)}</div><div class="muted sm">Fonti: ${H(LOSS_REFS)}${l.rad ? "; regola degli elettroni pari: Holčapek 2010" : ""}</div></div></div>`;
  };
  function lossList() {
    const hit = new Set(), q = parseFloat(String(NL.q).replace(",", "."));
    const vis = LOSSES.filter(l => !NL.pol || l.pol === "±" || l.pol === NL.pol).sort((a, b) => massOf(a.f) - massOf(b.f));
    if (isFinite(q)) vis.forEach(l => { if (Math.abs(massOf(l.f) - q) <= 0.5) hit.add(l.f); });
    const groups = []; vis.forEach(l => { const n = Math.round(massOf(l.f)), g = groups[groups.length - 1]; if (g && g.n === n) g.ls.push(l); else groups.push({ n, ls: [l] }); });
    return groups.map(g => g.ls.length < 2 ? lossRow(g.ls[0], { hit }) : `<div class="nlg"><div class="nlgn">Stessa massa nominale (${g.n}): a risoluzione unitaria non si distinguono, servono altri indizi.${g.n === 80 ? ` Controlla <i>M+2</i> con il profilo isotopico nello spettro (clic destro; Br: M e M+2 quasi uguali).` : ""}</div>${g.ls.map(l => lossRow(l, { hit })).join("")}</div>`).join("");
  }
  function lossCombosHtml() {
    const q = parseFloat(String(NL.q).replace(",", ".")); if (!isFinite(q) || q <= 0) return "";
    const c = lossCombos(q, massOf), nm = l => `<b>${fl(l.f)}</b>`;
    const li = [...c.single.map(x => `<li>${nm(x[0])} <span class="muted">(${massOf(x[0].f).toFixed(1)})</span></li>`), ...c.pairs.map(p => `<li>${nm(p[0])} + ${nm(p[1])} <span class="muted">(${(massOf(p[0].f) + massOf(p[1].f)).toFixed(1)})</span></li>`), ...c.reps.map(r => `<li>${r.n} &times; ${nm(r.l)} <span class="muted">(${(r.n * massOf(r.l.f)).toFixed(1)})</span></li>`)];
    return `<div class="nlc"><b>Possibili perdite (da verificare sullo spettro)</b>${li.length ? `<ul>${li.join("")}</ul>` : `<div class="muted sm">Nessuna perdita o combinazione della lista entro &plusmn;0.5.</div>`}</div>`;
  }
  function lossTab() {
    return `<div class="nlbar"><label>Cerca &Delta;m <input id="nl-q" inputmode="decimal" autocomplete="off" placeholder="es. 62" value="${H(NL.q)}" title="Scrivi la differenza di massa osservata: evidenzia le perdite con quel valore (±0.5) e mostra coppie e ripetizioni che la compongono"></label>
      <span class="seg" id="nl-pol" title="Polarità tipica della perdita"><button data-p="+" class="${NL.pol === "+" ? "on" : ""}">+</button><button data-p="-" class="${NL.pol === "-" ? "on" : ""}">&minus;</button><button data-p="" class="${NL.pol === "" ? "on" : ""}">tutte</button></span></div>
      <div id="nl-res">${lossCombosHtml()}</div><div id="nl-list">${lossList()}</div>` + lossRefs();
  }
  function bindLoss(root, show) {
    const list = () => { root.querySelector("#nl-list").innerHTML = lossList(); wire(); root.querySelector("#nl-res").innerHTML = lossCombosHtml(); };
    const wire = () => {
      root.querySelectorAll(".nld").forEach(b => b.onclick = () => { const id = b.dataset.d, row = b.closest(".nlr"), d = row.querySelector(".nldet"); if (NL.open.has(id)) NL.open.delete(id); else NL.open.add(id); d.hidden = !NL.open.has(id); b.setAttribute("aria-expanded", NL.open.has(id)); });
      root.querySelectorAll("[data-go]").forEach(a => a.onclick = e => { e.preventDefault(); show(a.dataset.go); });
    };
    wire();
    root.querySelector("#nl-q").oninput = e => { NL.q = e.target.value; list(); };
    root.querySelectorAll("#nl-pol button").forEach(b => b.onclick = () => { NL.pol = b.dataset.p; root.querySelectorAll("#nl-pol button").forEach(x => x.classList.toggle("on", x === b)); list(); });
  }
  // the polarity of the loaded files sets the filter when the window opens (the student can change it)
  function lossPolStart() {
    try { const fl = typeof shown === "function" && shown().length ? shown() : E.files.filter(f => f.vis), pos = fl.some(f => f.polarity === "positive"), neg = fl.some(f => f.polarity === "negative"); NL.pol = pos && !neg ? "+" : neg && !pos ? "-" : ""; } catch (_) { NL.pol = ""; }
  }

  // ---------------------------------------------------------------- isotope pattern, computed here (no external library)
  // Unit resolution: isotopologues are grouped by nominal mass offset (M, M+1, M+2...); in each group we keep the total
  // probability and the probability-weighted exact mass. Elements are combined by convolution (n atoms: by squaring).
  const counts = f => { const n = {}; for (const [, s, k] of f.matchAll(/([A-Z][a-z]?)(\d*)/g)) n[s] = (n[s] || 0) + (k ? +k : 1); return n; };
  const PRUNE = 1e-9, MAXOFF = 40;
  function conv(a, b) {                                    // a, b: Map(offset -> [probability, mass x probability])
    const out = new Map();
    for (const [oa, [pa, ma]] of a) for (const [ob, [pb, mb]] of b) {
      const o = oa + ob; if (o > MAXOFF) continue;
      const p = pa * pb; if (p < PRUNE) continue;
      const cur = out.get(o) || [0, 0];
      cur[0] += p; cur[1] += ma * pb + mb * pa;            // mean mass of the group adds up: E[ma+mb]
      out.set(o, cur);
    }
    return out;
  }
  function elementDist(s) {
    const e = EL[s]; if (!e || !e.iso.length) throw new Error(`abbondanze isotopiche non disponibili per ${s}`);
    const main = e.iso.reduce((a, b) => (b[2] > a[2] ? b : a)), d = new Map();
    for (const [A, m, pct] of e.iso) { const p = pct / 100; if (m == null || p <= 0) continue; const o = A - main[0]; d.set(o, [p, m * p]); }
    // keep only non-negative offsets relative to the lightest isotope: shift so the lightest is 0
    const o0 = Math.min(...d.keys()), out = new Map(); for (const [o, v] of d) out.set(o - o0, v); return out;
  }
  function power(d, n) {
    let res = new Map([[0, [1, 0]]]), base = d;
    while (n > 0) { if (n & 1) res = conv(res, base); n >>= 1; if (n) base = conv(base, base); }
    return res;
  }
  // pattern of an ion: element counts (already including the adduct) and charge z -> [{off, mz, rel}] (rel: % of the highest)
  function isoPattern(n, z = 1) {
    let dist = new Map([[0, [1, 0]]]);
    for (const [s, k] of Object.entries(n)) if (k > 0) dist = conv(dist, power(elementDist(s), k));
    const rows = [...dist].map(([o, [p, mp]]) => ({ off: o, p, mz: (mp / p - z * ELECTRON) / Math.abs(z) }));
    const top = Math.max(...rows.map(r => r.p));
    return rows.map(r => ({ off: r.off, mz: r.mz, rel: 100 * r.p / top })).filter(r => r.rel >= 0.05).sort((a, b) => a.mz - b.mz);
  }
  // neutral formula (Hill, no parentheses) + adduct name -> element counts of the ion and its charge
  function ionCounts(formula, adName) {
    const a = ADD.find(x => x.n === adName) || ADD[0], n = {}, M = counts(formula);
    for (const [s, k] of Object.entries(M)) n[s] = k * a.k;
    if (a.add) for (const [s, k] of Object.entries(counts(a.add))) n[s] = (n[s] || 0) + k;
    if (a.sub) for (const [s, k] of Object.entries(counts(a.sub))) n[s] = (n[s] || 0) - k;
    if (Object.values(n).some(k => k < 0)) throw new Error("l'addotto toglie più atomi di quanti ce ne sono");
    return { n, z: a.z, ad: a.n };
  }
  // ---------------------------------------------------------------- dialog with three tabs (Tavola periodica, Addotti, Perdite neutre)
  const TABS = [["pt", "Tavola periodica", periodic, bindPeriodic], ["ad", "Addotti", adductTab, bindAdducts], ["ls", "Perdite neutre", lossTab, bindLoss]];
  function open(which, opt = {}) {
    const d = Qs("#refdlg"), body = Qs("#refbody");
    if (which === "ls") { if (!d.open) lossPolStart(); if (opt.q != null) NL.q = String(opt.q); }
    const show = id => {
      const t = TABS.find(x => x[0] === id); body.innerHTML = t[2](); if (t[3]) t[3](body, show);
      d.querySelectorAll("#reftabs button").forEach(b => b.classList.toggle("on", b.dataset.t === id));
    };
    Qs("#reftabs").innerHTML = TABS.map(t => `<button data-t="${t[0]}">${t[1]}</button>`).join("");
    Qs("#reftabs").querySelectorAll("button").forEach(b => b.onclick = () => show(b.dataset.t));
    Qs("#refx").onclick = () => d.close();
    show(which); if (!d.open) d.showModal();
  }
  Qs("#np-pt").onclick = () => open("pt");
  Qs("#np-ad").onclick = () => open("ad");
  Qs("#np-nl").onclick = () => open("ls");
  window.QQQRef = { open, massOf, mono, isoPattern, ionCounts, ADD };
})();
