"use strict";
// Reference tables (header buttons "Tavola periodica" and "Addotti"): periodic table with isotopes, ESI adducts, isotope pattern
// of a formula (computed here), common neutral losses.
// Data of the elements: elements.js (generated by tools/genera_elementi.py). Classic script, after explore.js.
(() => {
  const Qs = s => document.querySelector(s), H = t => String(t).replace(/[&<>"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
  const ELECTRON = 0.00054858;
  const EL = Object.fromEntries(ELEMENTS.map(e => [e.s, e]));
  // layout of the periodic table: fixed row heights, so the table never changes size; the info box scrolls if needed
  const css = document.createElement("style");
  css.textContent = ".pt{grid-template-rows:repeat(7,46px) 12px repeat(2,46px)!important}.pt-c{height:46px;min-height:0!important;overflow:hidden}" +
    ".pt-info{height:144px;max-height:none!important;min-height:0;overflow:auto;font-size:11px!important;line-height:1.3;padding:2px 10px!important}" +
    ".pt-info table th,.pt-info table td{padding:0 6px!important}.pt-info .pt-big b{font-size:22px}";
  document.head.appendChild(css);
  // monoisotopic mass of an element = exact mass of its most abundant isotope
  const mono = s => { const e = EL[s]; if (!e || !e.iso.length) return null; return e.iso.reduce((a, b) => (b[2] > a[2] ? b : a))[1]; };
  function massOf(f) {                                     // simple formulas, e.g. "CH3COO", "C2H3N"
    let m = 0;
    for (const [, s, n] of f.matchAll(/([A-Z][a-z]?)(\d*)/g)) { const v = mono(s); if (v == null) throw new Error(s); m += v * (n ? +n : 1); }
    return m;
  }
  const sub = f => H(f).replace(/(\d+)/g, "<sub>$1</sub>");

  // ---------------------------------------------------------------- periodic table
  const ORGANIC = new Set(["H", "C", "N", "O", "F", "P", "S", "Cl", "Br", "I", "Na", "K", "Si"]);
  function info(e) {
    const main = e.iso.length ? e.iso.reduce((a, b) => (b[2] > a[2] ? b : a)) : null;
    let h = `<div class="pt-big"><span>${e.z}</span><b>${H(e.s)}</b></div><div><b style="font-size:15px">${H(e.n)}</b></div>
      <div>peso atomico medio <b>${e.w != null ? e.w : "n.d."}</b> <span class="muted">(media pesata sugli isotopi naturali)</span></div>`;
    if (main) {
      h += `<div>massa monoisotopica <b>${main[1].toFixed(5)}</b> <span class="muted">(<sup>${main[0]}</sup>${H(e.s)}, l'isotopo più abbondante: è quella che si usa in MS)</span></div>
        <table class="sm" style="margin-top:6px"><tr><th>isotopo</th><th class="num">massa esatta</th><th class="num">abbondanza %</th><th class="num">&Delta; dal principale</th><th></th></tr>` +
        e.iso.map(i => `<tr><td><sup>${i[0]}</sup>${H(e.s)}</td><td class="num">${i[1] != null ? i[1].toFixed(5) : ""}</td><td class="num">${i[2]}</td>` +
          `<td class="num">${i === main || i[1] == null ? "" : (i[1] - main[1] > 0 ? "+" : "") + (i[1] - main[1]).toFixed(4)}</td>` +
          `<td><i class="pt-bar" style="width:${Math.max(1, Math.round(i[2] * 0.8))}px"></i></td></tr>`).join("") + "</table>";
      if (e.iso.length > 1) {
        const sec = e.iso.filter(i => i !== main).reduce((a, b) => (b[2] > a[2] ? b : a));
        h += `<div class="muted sm" style="margin-top:4px">Ogni atomo di ${H(e.s)} nella molecola dà un picco a ${sec[0] - main[0] > 0 ? "+" : ""}${sec[0] - main[0]} con circa il ${(100 * sec[2] / main[2]).toFixed(sec[2] / main[2] < 0.1 ? 1 : 0)}% dell'intensità del picco principale.</div>`;
      }
    } else h += `<div class="muted sm" style="margin-top:6px">Elemento raro in LC-MS: abbondanze isotopiche non incluse nel programma.</div>`;
    return h;
  }
  function periodic() {
    const cells = ELEMENTS.map(e => `<div class="pt-c${ORGANIC.has(e.s) ? " org" : ""}${e.iso.length ? "" : " nd"}" data-s="${e.s}" style="grid-row:${e.r};grid-column:${e.c}">` +
      `<span>${e.z}</span><b>${e.s}</b><small>${e.w != null ? (e.w < 100 ? e.w.toFixed(3) : e.w.toFixed(2)) : ""}</small></div>`).join("");
    // Data sources (kept here, not shown in the page): exact masses = isotope table of OpenChemLib; abundances = representative
    // isotopic compositions, IUPAC (CIAAW); average atomic weight = Ketcher element list. Hovering an element shows masses and isotopes
    // (click pins it); the most common elements of organic molecules are highlighted.
    return `<div class="pt">${cells}<div class="pt-info" id="pt-info">${info(EL.C)}</div><div class="pt-gap">lantanidi e attinidi</div></div>`;
  }
  function bindPeriodic(root) {
    let pinned = null; const box = root.querySelector("#pt-info");
    root.querySelectorAll(".pt-c").forEach(c => {
      c.onmouseenter = () => { if (!pinned) box.innerHTML = info(EL[c.dataset.s]); };
      c.onclick = () => { root.querySelectorAll(".pt-c.pin").forEach(x => x.classList.remove("pin")); if (pinned === c.dataset.s) { pinned = null; return; }
        pinned = c.dataset.s; c.classList.add("pin"); box.innerHTML = info(EL[pinned]); };
    });
  }

  // ---------------------------------------------------------------- adducts
  // k: how many molecules M; add/sub: what is added or removed; z: charge
  const ADD = [
    { n: "[M+H]+", k: 1, add: "H", z: 1, note: "lo ione più comune in ESI+ con acido formico in fase mobile (come in questo laboratorio)" },
    { n: "[M+NH4]+", k: 1, add: "NH4", z: 1, note: "con sali di ammonio (formiato, acetato) in fase mobile; tipico di esteri, chetoni, zuccheri" },
    { n: "[M+Na]+", k: 1, add: "Na", z: 1, note: "sodio da vetreria, acqua, campione: frequentissimo; frammenta poco in MS/MS" },
    { n: "[M+K]+", k: 1, add: "K", z: 1, note: "come il sodio, meno intenso" },
    { n: "[M+H-H2O]+", k: 1, add: "H", sub: "H2O", z: 1, note: "perdita d'acqua in sorgente (alcoli, acidi carbossilici)" },
    { n: "[M+CH3OH+H]+", k: 1, add: "CH5O", z: 1, note: "con metanolo in fase mobile" },
    { n: "[M+ACN+H]+", k: 1, add: "C2H4N", z: 1, note: "con acetonitrile in fase mobile" },
    { n: "[M+2H]2+", k: 1, add: "H2", z: 2, note: "carica doppia: m/z circa dimezzato, isotopi distanti 0.5" },
    { n: "[2M+H]+", k: 2, add: "H", z: 1, note: "dimero: compare a concentrazioni alte" },
    { n: "[2M+Na]+", k: 2, add: "Na", z: 1, note: "dimero con sodio" },
    { n: "[M]+", k: 1, add: "", z: 1, note: "molecola già carica (es. ammonio quaternario) o radicale catione M<sup>+&bull;</sup>" },
    { n: "[M-H]-", k: 1, sub: "H", z: -1, note: "lo ione più comune in ESI&minus; (acidi, fenoli, sulfonati)" },
    { n: "[M+Cl]-", k: 1, add: "Cl", z: -1, note: "con solventi clorurati o campioni salini (cerca la coppia 35/37 a 3:1)" },
    { n: "[M+HCOO]-", k: 1, add: "CHO2", z: -1, note: "con acido formico in fase mobile" },
    { n: "[M+CH3COO]-", k: 1, add: "C2H3O2", z: -1, note: "con acido acetico o acetato di ammonio" },
    { n: "[M-H-H2O]-", k: 1, sub: "H3O", z: -1, note: "perdita d'acqua in sorgente" },
    { n: "[M+Na-2H]-", k: 1, add: "Na", sub: "H2", z: -1, note: "sale sodico" },
    { n: "[M-2H]2-", k: 1, sub: "H2", z: -2, note: "carica doppia" },
    { n: "[2M-H]-", k: 2, sub: "H", z: -1, note: "dimero" },
  ];
  ADD.forEach(a => { a.shift = (a.add ? massOf(a.add) : 0) - (a.sub ? massOf(a.sub) : 0) - a.z * ELECTRON; });
  const mzOf = (a, M) => (a.k * M + a.shift) / Math.abs(a.z);
  const fmtAd = n => H(n).replace(/([A-Z][a-z]?|\))(\d+)/g, "$1<sub>$2</sub>").replace(/(\d?[+-])$/, "<sup>$1</sup>");
  function adducts(M) {
    const ref = { 1: ADD[0], "-1": ADD.find(a => a.n === "[M-H]-") };
    const rows = pol => ADD.filter(a => Math.sign(a.z) === pol).map(a => {
      const expr = `${a.k > 1 ? a.k : ""}M ${a.shift >= 0 ? "+" : "&minus;"} ${Math.abs(a.shift).toFixed(4)}${Math.abs(a.z) > 1 ? `, diviso ${Math.abs(a.z)}` : ""}`;
      const d = a === ref[pol] || Math.abs(a.z) > 1 || a.k > 1 ? "" : ((a.shift - ref[pol].shift) >= 0 ? "+" : "&minus;") + Math.abs(a.shift - ref[pol].shift).toFixed(4);
      return `<tr><td><b>${fmtAd(a.n)}</b></td><td>${expr}</td><td class="num">${M != null ? mzOf(a, M).toFixed(4) : ""}</td><td class="num">${M != null ? mzOf(a, M).toFixed(1) : ""}</td><td class="num">${d}</td><td class="muted sm">${a.note}</td></tr>`;
    }).join("");
    const head = pol => `<tr><th>addotto</th><th>m/z =</th><th class="num">m/z esatto</th><th class="num">1 decimale</th><th class="num">&Delta; da ${pol > 0 ? "[M+H]<sup>+</sup>" : "[M&minus;H]<sup>&minus;</sup>"}</th><th>quando si vede</th></tr>`;
    return `<h4>ESI positivo</h4><table>${head(1)}${rows(1)}</table><h4>ESI negativo</h4><table>${head(-1)}${rows(-1)}</table>`;
  }
  function adductTab() {
    return `<div class="bar"><label>M (massa neutra) o formula <input id="ad-in" placeholder="es. 363.0665 oppure C14H13F4N3O2S" style="width:260px"></label><span id="ad-msg" class="muted sm"></span></div>
      <div class="muted sm">M = massa esatta monoisotopica della molecola neutra. La colonna &Delta; aiuta a riconoscere gli addotti nello spettro: per esempio un picco 21.98 sopra [M+H]<sup>+</sup> è quasi sempre [M+Na]<sup>+</sup>.</div>
      <div id="ad-tbl">${adducts(null)}</div>`;
  }
  function bindAdducts(root) {
    const inp = root.querySelector("#ad-in"), msg = root.querySelector("#ad-msg"), tb = root.querySelector("#ad-tbl");
    inp.oninput = async () => {
      const t = inp.value.trim().replace(",", ".");
      if (!t) { msg.textContent = ""; tb.innerHTML = adducts(null); return; }
      if (/^\d+(\.\d*)?$/.test(t)) { msg.textContent = ""; tb.innerHTML = adducts(+t); return; }
      try { const r = await (await fetch("api/formula?f=" + encodeURIComponent(t))).json(); if (r.error) throw new Error(r.error);
        let M = r.neutral; try { M = massOf(r.formula); } catch (_) { /* element without isotope data here: use the server value */ }
        msg.innerHTML = `${sub(r.formula)}: M = ${M.toFixed(4)}`; tb.innerHTML = adducts(M); }
      catch (e) { msg.textContent = "formula non valida"; tb.innerHTML = adducts(null); }
    };
  }

  // ---------------------------------------------------------------- common neutral losses (MS/MS and in-source)
  const LOSS = [["H2O", "acqua: alcoli, acidi carbossilici"], ["NH3", "ammine primarie, ammidi"], ["CO", "chetoni, aldeidi, fenoli"], ["CO2", "acidi carbossilici"],
    ["CH2O", "formaldeide: alcoli benzilici, metossi"], ["CH4O", "metanolo: esteri metilici, metossi"], ["C2H2O", "chetene: acetammidi, acetati"], ["HCOOH", "acido formico: acidi"],
    ["C2H4", "etilene: catene etiliche, eteri etilici"], ["C3H6", "propene: gruppi isopropilici"], ["HCN", "acido cianidrico: nitrili, eterocicli azotati"],
    ["HF", "composti fluorurati"], ["HCl", "composti clorurati"], ["HBr", "composti bromurati"], ["SO2", "sulfonammidi, solfoni"], ["SO3", "solfati, sulfonati"],
    ["H2S", "tioli, tioeteri"], ["CH3", "radicale metile (perdita dispari, poco comune in ESI)"], ["NO2", "radicale NO2: nitroderivati"], ["C6H6", "benzene: anelli aromatici"]];
  // The masses are computed from the formulas (exact mass rounded to the integer); the "typical of" column summarises what the reviews below
  // describe for even-electron ions in ESI-MS/MS. A loss is only a hypothesis: it must be checked against the structure.
  function lossRefs() {
    const L = (u, t) => `<a href="${u}" target="_blank" rel="noopener">${t}</a>`;
    return `<div class="muted sm" style="margin-top:8px"><b>Riferimenti</b><ol style="margin:4px 0 0 18px;padding:0;line-height:1.5">
      <li>Levsen K., Schiebel H.-M., Terlouw J. K., et al. <i>Even-electron ions: a systematic study of the neutral species lost in the dissociation of quasi-molecular ions.</i> J. Mass Spectrom. 2007, 42, 1024-1044. ${L("https://analyticalsciencejournals.onlinelibrary.wiley.com/doi/10.1002/jms.1234", "link")}</li>
      <li>De Vijlder T., Valkenborg D., Lemi&egrave;re F., Romijn E. P., Laukens K., Cuyckens F. <i>A tutorial in small molecule identification via electrospray ionization-mass spectrometry: the practical art of structural elucidation.</i> Mass Spectrom. Rev. 2018, 37, 607-629. ${L("https://pmc.ncbi.nlm.nih.gov/articles/PMC6099382/", "link (accesso libero)")}</li>
      <li>Demarque D. P., Crotti A. E. M., Vessecchi R., Lopes J. L. C., Lopes N. P. <i>Fragmentation reactions using electrospray ionization mass spectrometry: an important tool for the structural elucidation and characterization of synthetic and natural products.</i> Nat. Prod. Rep. 2016, 33, 432-455. ${L("https://pubs.rsc.org/en/content/articlelanding/2016/np/c5np00073d", "link")}</li>
      <li>Hol&ccaron;apek M., Jir&aacute;sko R., L&iacute;sa M. <i>Basic rules for the interpretation of atmospheric pressure ionization mass spectra of small molecules.</i> J. Chromatogr. A 2010, 1217, 3908-3921. ${L("https://pubmed.ncbi.nlm.nih.gov/20303090/", "link")}</li></ol></div>`;
  }
  function lossTab() {
    return `<table><tr><th>perdita</th><th class="num">&Delta;m</th><th>tipica di</th></tr>` +
      LOSS.map(([f, n]) => { const m = massOf(f); return `<tr><td><b>${sub(f)}</b></td><td class="num"><b>${Math.round(m)}</b></td><td class="muted sm">${n}</td></tr>`; }).join("") + "</table>" + lossRefs();
  }

  // ---------------------------------------------------------------- isotope pattern, computed here (no external library)
  // Unit resolution: isotopologues are grouped by nominal mass offset (M, M+1, M+2...); in each group we keep the total
  // probability and the probability-weighted exact mass. Elements are combined by convolution (n atoms: by squaring).
  const counts = f => { const n = {}; for (const [, s, k] of f.matchAll(/([A-Z][a-z]?)(\d*)/g)) n[s] = (n[s] || 0) + (k ? +k : 1); return n; };
  const PRUNE = 1e-9, MAXOFF = 40;
  function conv(a, b) {                                    // a, b: Map(offset -> [probability, mass x probability])
    const out = new Map();
    for (const [oa, [pa, ma]] of a) for (const [ob, [pb, mb]] of b) {
      const o = oa + ob; if (o > MAXOFF) continue;
      const p = pa * pb; if (p < PRUNE) continue;
      const cur = out.get(o) || [0, 0];
      cur[0] += p; cur[1] += ma * pb + mb * pa;            // mean mass of the group adds up: E[ma+mb]
      out.set(o, cur);
    }
    return out;
  }
  function elementDist(s) {
    const e = EL[s]; if (!e || !e.iso.length) throw new Error(`abbondanze isotopiche non disponibili per ${s}`);
    const main = e.iso.reduce((a, b) => (b[2] > a[2] ? b : a)), d = new Map();
    for (const [A, m, pct] of e.iso) { const p = pct / 100; if (m == null || p <= 0) continue; const o = A - main[0]; d.set(o, [p, m * p]); }
    // keep only non-negative offsets relative to the lightest isotope: shift so the lightest is 0
    const o0 = Math.min(...d.keys()), out = new Map(); for (const [o, v] of d) out.set(o - o0, v); return out;
  }
  function power(d, n) {
    let res = new Map([[0, [1, 0]]]), base = d;
    while (n > 0) { if (n & 1) res = conv(res, base); n >>= 1; if (n) base = conv(base, base); }
    return res;
  }
  // pattern of an ion: element counts (already including the adduct) and charge z -> [{off, mz, rel}] (rel: % of the highest)
  function isoPattern(n, z = 1) {
    let dist = new Map([[0, [1, 0]]]);
    for (const [s, k] of Object.entries(n)) if (k > 0) dist = conv(dist, power(elementDist(s), k));
    const rows = [...dist].map(([o, [p, mp]]) => ({ off: o, p, mz: (mp / p - z * ELECTRON) / Math.abs(z) }));
    const top = Math.max(...rows.map(r => r.p));
    return rows.map(r => ({ off: r.off, mz: r.mz, rel: 100 * r.p / top })).filter(r => r.rel >= 0.05).sort((a, b) => a.mz - b.mz);
  }
  // neutral formula (Hill, no parentheses) + adduct name -> element counts of the ion and its charge
  function ionCounts(formula, adName) {
    const a = ADD.find(x => x.n === adName) || ADD[0], n = {}, M = counts(formula);
    for (const [s, k] of Object.entries(M)) n[s] = k * a.k;
    if (a.add) for (const [s, k] of Object.entries(counts(a.add))) n[s] = (n[s] || 0) + k;
    if (a.sub) for (const [s, k] of Object.entries(counts(a.sub))) n[s] = (n[s] || 0) - k;
    if (Object.values(n).some(k => k < 0)) throw new Error("l'addotto toglie più atomi di quanti ce ne sono");
    return { n, z: a.z, ad: a.n };
  }
  function isoTab() {
    return `<div class="bar"><label>Formula <input id="is-f" placeholder="es. C14H13F4N3O2S" style="width:220px"></label>
      <label>Addotto <select id="is-ad">${ADD.map(a => `<option>${H(a.n)}</option>`).join("")}</select></label><span id="is-msg" class="muted sm"></span></div>
      <div class="muted sm">Profilo isotopico calcolato dalla formula che scrivi tu (abbondanze naturali), come lo vede uno strumento a risoluzione unitaria: un picco per ogni massa intera (M, M+1, M+2...). Confrontalo con lo spettro: un cloro dà M+2 circa un terzo di M, un bromo M+2 alto quasi come M, lo zolfo un M+2 piccolo (4-5%). Nello spettro, clic destro &rarr; &laquo;Confronta con il profilo isotopico&raquo; lo disegna sopra i picchi.</div>
      <div id="is-out"></div>`;
  }
  // stick spectrum of the pattern (m/z on x, relative intensity on y): every peak M, M+1, M+2... is a stem with its label and percentage
  function isoSvg(rows) {
    const w = 620, h = 200, l = 44, r = 14, t = 22, b = 36, lo = Math.min(...rows.map(q => q.mz)) - 1, hi = Math.max(...rows.map(q => q.mz)) + 1;
    const X = v => l + (v - lo) / (hi - lo) * (w - l - r), Y = v => t + (100 - v) / 100 * (h - t - b), ink = "#6b7280", bar = "#2b5c8a";
    let g = `<svg viewBox="0 0 ${w} ${h}" width="100%" style="max-width:${w}px;background:#fff;border:1px solid #d8dde6;border-radius:6px;margin-top:6px" font-family="system-ui" font-size="11"><path d="M${l} ${t - 6}V${h - b}H${w - r}" fill="none" stroke="${ink}"/>`;
    for (const v of [0, 25, 50, 75, 100]) g += `<path d="M${l - 3} ${Y(v)}H${l}" stroke="${ink}"/><text x="${l - 6}" y="${Y(v) + 4}" text-anchor="end" fill="${ink}">${v}</text>`;
    for (let v = Math.ceil(lo); v <= hi; v++) g += `<path d="M${X(v)} ${h - b}v3" stroke="${ink}"/><text x="${X(v)}" y="${h - b + 15}" text-anchor="middle" fill="${ink}">${v}</text>`;
    for (const q of rows) {
      const lab = (q.off ? "M+" + q.off : "M"), pc = q.rel < 1 ? q.rel.toFixed(2) : q.rel.toFixed(1);
      g += `<path d="M${X(q.mz)} ${Y(0)}V${Y(q.rel)}" stroke="${bar}" stroke-width="3"/><text x="${X(q.mz)}" y="${Y(q.rel) - 14}" text-anchor="middle" fill="#1f2937" font-weight="600">${lab}</text><text x="${X(q.mz)}" y="${Y(q.rel) - 3}" text-anchor="middle" fill="${ink}">${pc}%</text>`;
    }
    return g + `<text x="${(l + w - r) / 2}" y="${h - 4}" text-anchor="middle" fill="#1f2937">m/z</text><text transform="translate(12 ${(t + h - b) / 2}) rotate(-90)" text-anchor="middle" fill="#1f2937">Intensità relativa (%)</text></svg>`;
  }
  function isoHtml(rows) {
    return isoSvg(rows) + `<table style="margin-top:6px;max-width:560px"><tr><th>picco</th><th class="num">m/z</th><th class="num">1 decimale</th><th class="num">intensità relativa %</th><th></th></tr>` +
      rows.map(r => `<tr><td>${r.off ? "M+" + r.off : "M"}</td><td class="num">${r.mz.toFixed(4)}</td><td class="num">${r.mz.toFixed(1)}</td><td class="num"><b>${r.rel < 1 ? r.rel.toFixed(2) : r.rel.toFixed(1)}</b></td>` +
      `<td><i class="pt-bar" style="width:${Math.max(1, Math.round(r.rel * 2))}px"></i></td></tr>`).join("") + "</table>";
  }
  function bindIso(root) {
    const f = root.querySelector("#is-f"), ad = root.querySelector("#is-ad"), msg = root.querySelector("#is-msg"), out = root.querySelector("#is-out");
    const run = async () => {
      const t = f.value.trim(); if (!t) { out.innerHTML = ""; msg.textContent = ""; return; }
      try {
        const r = await (await fetch("api/formula?f=" + encodeURIComponent(t))).json(); if (r.error) throw new Error("formula non valida");
        const ion = ionCounts(r.formula, ad.value); msg.innerHTML = sub(r.formula) + " " + H(ion.ad);
        out.innerHTML = isoHtml(isoPattern(ion.n, ion.z));
      } catch (e) { msg.textContent = e.message; out.innerHTML = ""; }
    };
    f.oninput = run; ad.onchange = run;
  }

  // ---------------------------------------------------------------- dialog with three tabs
  const TABS = [["pt", "Tavola periodica", periodic, bindPeriodic], ["ad", "Addotti", adductTab, bindAdducts], ["is", "Isotopi", isoTab, bindIso], ["ls", "Perdite neutre", lossTab, null]];
  function open(which) {
    const d = Qs("#refdlg"), body = Qs("#refbody");
    const show = id => {
      const t = TABS.find(x => x[0] === id); body.innerHTML = t[2](); if (t[3]) t[3](body);
      d.querySelectorAll("#reftabs button").forEach(b => b.classList.toggle("on", b.dataset.t === id));
    };
    Qs("#reftabs").innerHTML = TABS.map(t => `<button data-t="${t[0]}">${t[1]}</button>`).join("");
    Qs("#reftabs").querySelectorAll("button").forEach(b => b.onclick = () => show(b.dataset.t));
    Qs("#refx").onclick = () => d.close();
    show(which); if (!d.open) d.showModal();
  }
  Qs("#np-pt").onclick = () => open("pt");
  Qs("#np-ad").onclick = () => open("ad");
  window.QQQRef = { open, massOf, mono, isoPattern, ionCounts, ADD };
})();
