"""Builds qqq_lab/web/teoria/glossario-dati.js from the glossary chapter (21-glossario.html).

The Teoria pages use it to underline every glossary term in the text and show a short definition when the mouse is over it.
Edit the glossary in 21-glossario.html, then run from the project root:  python3 tools/genera_glossario.py
Rules: a <dt> may hold several names (separated by ' / ' or ', ', or a name plus a short acronym in brackets); names with
sub/superscripts are skipped (they do not exist as plain text in the pages); OVERRIDE lists names by hand where the rule
does not fit, EXTRA adds plurals and variants.
"""
import json, re
from pathlib import Path

D = Path(__file__).resolve().parents[1] / "qqq_lab" / "web" / "teoria"
OVERRIDE = {
    "a, q (parametri di Mathieu)": ["parametri di Mathieu"],
    "Mathieu (equazione di)": ["equazione di Mathieu", "Mathieu"],
    "Retta di lavoro (scan line)": ["retta di lavoro", "scan line"],
    "Full scan (Q1 MS)": ["full scan", "Q1 MS"],
    "Massa nominale / monoisotopica": ["massa nominale", "massa monoisotopica"],
    "Affinità protonica (PA)": ["affinità protonica", "PA"],
    "CUR (curtain gas)": ["CUR", "curtain gas"],
    "Van Deemter (equazione di)": ["equazione di van Deemter", "van Deemter"],
    "McLafferty (riarrangiamento di)": ["riarrangiamento di McLafferty", "McLafferty"],
    "Indice di ritenzione / indice di Kováts": ["indice di ritenzione", "indice di Kováts", "indici di ritenzione"],
    "Accuratezza di massa / errore in ppm": ["accuratezza di massa", "errore in ppm"],
    "Tempo di volo (TOF)": ["tempo di volo", "TOF"],
    "Ionizzazione elettronica (EI)": ["ionizzazione elettronica", "EI"],
    "Ionizzazione chimica (CI)": ["ionizzazione chimica", "CI"],
}
EXTRA = {
    "Perdita neutra": ["perdite neutre"], "Picco base": ["picchi base"], "Ione precursore": ["ioni precursori", "precursore"],
    "Ione prodotto": ["ioni prodotto", "ioni prodotti"], "Transizione": ["transizioni"], "Addotto": ["addotti"],
    "Piatti teorici": ["piatti", "numero di piatti"], "Radicale catione": ["radicali cationi"],
    "Trappola ionica": ["trappole ioniche"], "Ione molecolare": ["ioni molecolari"],
}


def names(dt: str) -> list[str]:
    if dt in OVERRIDE:
        return OVERRIDE[dt]
    out = []
    for part in re.split(r"\s+/\s+|,\s+", dt):
        part = part.strip()
        m = re.match(r"^(.*?)\s*\((.*?)\)$", part)
        for x in ([m.group(1), m.group(2)] if m else [part]):
            if x and "<" not in x and len(x) >= 2:
                out.append(x)
    return out


def main() -> None:
    html = (D / "21-glossario.html").read_text(encoding="utf-8")
    items = []
    for dt, dd in re.findall(r"<dt>(.*?)</dt><dd>(.*?)</dd>", html, re.S):
        ns = [n for n in names(dt) if "<" not in n] + EXTRA.get(re.sub(r"<[^>]+>", "", dt), [])
        links = re.findall(r'<a href="([^"#]+)">(Cap\. [^<]+)</a>', dd)
        body = re.sub(r'\s*<a href="[^"]+">(?:Cap\.|\d)[^<]*</a>(?:,\s*)?', "", dd).strip()
        if ns and body:
            items.append({"k": ns, "t": dt, "d": body, "h": links[0][0] if links else "", "n": links[0][1] if links else ""})
    (D / "glossario-dati.js").write_text(
        "// Generated by tools/genera_glossario.py from 21-glossario.html: do not edit by hand.\n"
        "const GLOSSARIO = [\n" + ",\n".join(json.dumps(i, ensure_ascii=False) for i in items) + "\n];\n", encoding="utf-8")
    print(len(items), "entries,", sum(len(i["k"]) for i in items), "names")


if __name__ == "__main__":
    main()
